### ISSUE TITLE
Ubuntu 20.04 install fails "Not: not found" after "Download complete" message.

### ISSUE THREAD

**Issue by vielmetti** [comtrya/comtrya#36]
New install on a Ubuntu 20.04 machine fails

```
root@bastion-01:~# curl -fsSL https://get.comtrya.dev | sh
x86_64
Downloading package https://github.com/rawkode/comtrya/releases/download/latest/comtrya-x86_64-unknown-linux-gnu as /tmp/comtrya-x86_64-unknown-linux-gnu
Download complete.

Running with sufficient permissions to attempt to move comtrya to /usr/local/bin
New version of comtrya installed to /usr/local/bin
/usr/local/bin/comtrya: 1: Not: not found
```

and it appears that the /tmp directory does not include `/tmp/comtrya-x86_64-unknown-linux-gnu`.

The contents of /usr/local/bin/comtrya when I'm done is

```
Not Found
```

**Comment by vielmetti** [comment]
I think this is due to the repo moving from `rawkode/comtrya` to `comtrya/comtrya`. This succeeds, so there should be an easy fix:

```
root@bastion-01:~# curl -fsSL https://get.comtrya.dev | sed -e 's/rawkode/comtrya/g' | sh
```
(not recommended for actual use)

**Comment by rawkode** [comment]
I've tagged a new release, this should publish the artifacts under the new org.

**Comment by rawkode** [comment]
@vielmetti I believe this is fixed. Please feel free to reopen if I am mistaken.

**Comment by muhannad0** [comment]
Hey there David,

I'm still getting the `OWNER` variable set as `OWNER=rawkode` in the install script.

Tried running `curl -vfsSL https://get.comtrya.dev` on a couple of servers at different regions to rule out caching. But it's still the same.

Here's an output with `curl -vfsSL https://get.comtrya.dev`
```
< HTTP/2 200
< date: Thu, 18 Mar 2021 14:37:05 GMT
< content-type: text/html; charset=utf-8
< content-disposition: inline; filename="index.html"
< cache-control: public, max-age=0, must-revalidate
< content-length: 4304
< access-control-allow-origin: *
< etag: W/"0dddf5ba5a84c7db6b3bfdb212ae3367aa5f8301a03eec7636fd22ec5831d728"
< accept-ranges: bytes
< x-vercel-cache: HIT
< age: 841
< server: Vercel
< x-vercel-id: iad1::swqmt-1616078225781-497a6847a487
< strict-transport-security: max-age=63072000
<
#!/usr/bin/env sh
## Kindly inspired by Arkade by Alex Ellis
## https://github.com/alexellis/arkade

export VERIFY_CHECKSUM=0
export ALIAS_NAME="comtrya"
export OWNER=rawkode
export REPO=comtrya
export SUCCESS_CMD="$REPO --help"
export BINLOCATION="/usr/local/bin"
```

I noticed that `x-vercel-cache` is marked as `HIT`. Do you think it might need a cache invalidation for the new update to take effect?

**Comment by rawkode** [comment]
Hi @muhannad0, I've flushed the cache on Cloudflare and Vercel. Sorry for that

**Comment by muhannad0** [comment]
Thanks @rawkode. All good now. 👍
